#spring.application.name=ex09
#
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3308/DB
#spring.datasource.username=root
#spring.datasource.password=1234
#
## create ???? none ???? ?? ???. update ???? ??? ??? ??
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true


#yml ????.
spring :
  application:
    name : ex09

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: url=jdbc:mariadb://localhost:3308/DB
    username : root
    password: 1234

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate.format_sql: true
      show-sql: true
      open-in-view: fales

my:
  value: "welcom to vasdfa"