#spring.application.name=ex10
#
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3308/DB
#spring.datasource.username=root
#spring.datasource.password=1234
#
## create ???? none ???? ?? ???. update ???? ??? ??? ??
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#yml ????.

server:
  port: 10000

spring:
  application:
    name: ex10
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://maria_container:3306/DB
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
my:
  value: "welcome to vasdfa"

servlet:
  multipart:
    max-file-size: 100MB
    min-file-size: 10MB

